# Generated by Django 3.0 on 2021-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210523_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='remaining_tablets',
            field=models.IntegerField(null=True),
        ),
    ]
