# Generated by Django 3.0 on 2021-05-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20210523_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.MedicineInfo'),
        ),
    ]
