# Generated by Django 3.0 on 2021-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinfo',
            name='org_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='medicineinfo',
            name='tablets_required',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
